Abort & show msg if require for serialport fails
With this little fix you can provide some worthy information to the user.

Error without the fix:
```
error: Connection failed SerialPort is not a constructor
```
What does this mean?!

Error with the fix:
```
Error requiring serialport Error: The module '[...]/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
Yep, that sounds like something I can fix :)